### ISSUE TITLE
adafruit ht16k33 breakout (arduino)

### ISSUE THREAD

**Issue by damopinn** [dmadison/Segmented-LED-Display-ASCII#1]
Hi your 16 segment font works great with adafruit backpack breakout board. I just pasted the data over the old data in Adafruit_LEDBackpack.cpp which is in the library folder. now the 14 segment demos work correctly with my 8 digit 16 segment display.
Thanks for sharing your hardwork!!!

**Comment by dmadison** [comment]
That's awesome! I'm glad you found them useful! :smile:
