### ISSUE TITLE
Segment order README.md

### ISSUE THREAD

**Issue by sarmientosaurus** [dmadison/Segmented-LED-Display-ASCII#5]
Description of segment order in README.md for 14-segment display has an error: L and N are mixed up.

**Comment by dmadison** [comment]
It looks accurate to me. Why do you think they are mixed up?

**Comment by dmadison** [comment]
I'm using [this Luckylight display](https://www.luckylight.cn/en/products/led-display/alphanumeric/kwa-541cvb/) (KWA-541CVB) for reference. The segment order in the README appears to be correct and matches the segment order in the LED arrays as well.

Closing due to no new information.
